builders:
  hive_builder:
    import: "package:repository_hive/hive_builder.dart"
    builder_factories: ["hiveBuilder"]
    build_extensions: { ".dart": [".hive.dart"] }
    auto_apply: all_packages
    build_to: source

targets:
  $default:
    builders:
      repository_hive|hive_builder:
        enabled: true
        generate_for:
          - lib/model/product.dart
          - lib/model/Item.dart
          - lib/model/manufacturer.dart
          - lib/model/inventory.dart
